services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: motorzap
      POSTGRES_PASSWORD: motorzap
      POSTGRES_DB: motorzap
  
  adminer:
    image: adminer:5
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: postgres