services:
  postgres:
    image: postgres:18
    container_name: motorzap-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: motorzap
      POSTGRES_PASSWORD: motorzap
      POSTGRES_DB: motorzap
    volumes:
      - pg_motorzap_data:/var/lib/postgresql
    networks:
      - motorzap-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U motorzap"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: motorzap-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - motorzap-network
    depends_on:
      - postgres

volumes:
  pg_motorzap_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  motorzap-network:
    driver: bridge